name: Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn install

      - name: build production project
        run: yarn run build:prod

      - name: linting ts
        run: yarn run lint:ts
      - name: linting scss
        run: yarn run lint:scss

      - name: unit testing
        run: yarn run test:unit


